"""Character-specific types layered over World storage."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field

from .common import CharacterRef, Json
from .state import CharacterState


class CharacterRole(StrEnum):
    PC = "pc"
    MAJOR_NPC = "major_npc"
    MINOR_NPC = "minor_npc"
    ENSEMBLE = "ensemble"
    NAMED_FLAVOR = "named_flavor"


class VoiceAnchor(BaseModel):
    summary: str = ""
    voice_register: str = ""  # 'formal', 'casual', 'archaic', 'low', 'technical', ...
    samples: list[str] = Field(default_factory=list)
    speech_patterns: list[str] = Field(default_factory=list)
    address_terms: dict[str, str] = Field(default_factory=dict)
    dos: list[str] = Field(default_factory=list)
    donts: list[str] = Field(default_factory=list)


class ImagePromptTemplate(BaseModel):
    base_prompt: str = ""
    negative_prompt: str = ""
    canonical_seed: int | None = None
    extra: Json = Field(default_factory=dict)


class CharacterImageKind(StrEnum):
    PORTRAIT = "portrait"  # canonical headshot / card-art
    AVATAR = "avatar"  # platform avatar (e.g. embedded in card PNG)
    EXPRESSION = "expression"  # mood/expression sheet (angry, smiling, ...)
    POSE = "pose"  # full-body pose / outfit
    SCENE = "scene"  # in-scene illustration
    REFERENCE = "reference"  # creator-supplied reference art


class CharacterImage(BaseModel):
    """A single image associated with a character, with usage hints.

    ``description`` answers "when should this image be used?" — e.g. "angry,
    fangs bared; for combat scenes" or "neutral portrait, library tier".
    The gallery covers both author-supplied art (the embedded card avatar,
    reference sheets) and images later generated by ImageGen.
    """

    path: str  # repo-relative or data-root-relative path, or external URI
    description: str = ""  # when to use it
    kind: CharacterImageKind = CharacterImageKind.PORTRAIT
    tags: list[str] = Field(default_factory=list)  # 'angry', 'rain', 'cloak-up', ...
    seed: int | None = None  # canonical seed if generated deterministically
    prompt_used: str = ""  # the actual prompt that produced this image
    source: str = ""  # 'embedded_avatar', 'generated', 'manual_upload', ...
    created_at: datetime | None = None
    extra: Json = Field(default_factory=dict)


class StructuralRelationship(BaseModel):
    """Library-level relationship recorded on the character card.

    ``to_ref`` may be a character reference (the common case) or a
    faction reference such as ``worlds/<s>/factions/<id>`` when the
    relationship is membership / leadership / rivalry with a faction. Use
    ``kind`` values like ``faction:member`` / ``faction:leader`` /
    ``faction:rival`` to disambiguate.
    """

    to_ref: CharacterRef
    kind: str  # 'spouse', 'sibling', 'mentor', 'ally', 'rival', 'faction:member', ...
    note: str = ""


class InternalThoughtsPrivacy(BaseModel):
    """Per-character internal-thought visibility (default all true).

    See docs/superpowers/specs/2026-05-19-transient-state-design.md §Privacy.
    """

    surface_in_hud: bool = True
    surface_inline: bool = True
    surface_in_context: bool = True


class CharacterPrivacy(BaseModel):
    """Privacy frontmatter owned by the transient-state subsystem.

    HUD / inline / context-builder all read through
    ``grimoire.transient_state.privacy.resolve`` to enforce visibility.
    """

    internal_thoughts: InternalThoughtsPrivacy = Field(default_factory=InternalThoughtsPrivacy)


class Character(BaseModel):
    """Library character read from a markdown file."""

    id: str
    name: str
    role: CharacterRole
    world_id: str | None = None  # None if campaign-local emergent
    aliases: list[str] = Field(default_factory=list)
    age: str | None = None
    tags: list[str] = Field(default_factory=list)
    voice: VoiceAnchor = Field(default_factory=VoiceAnchor)
    image: ImagePromptTemplate | None = None
    images: list[CharacterImage] = Field(default_factory=list)
    structural_relationships: list[StructuralRelationship] = Field(default_factory=list)
    description: str = ""
    body: str = ""
    file_path: str = ""
    file_mtime: datetime | None = None
    version: int = 0
    household_id: str | None = None
    """Optional household membership key (Time Engine §4 significance).
    Free-form; characters sharing the same value tick together when at least
    one member is a PC."""
    privacy: CharacterPrivacy = Field(default_factory=CharacterPrivacy)


class CharacterData(BaseModel):
    """Payload for create/import flows; lighter than `Character` (no file metadata)."""

    id: str
    name: str
    role: CharacterRole
    aliases: list[str] = Field(default_factory=list)
    age: str | None = None
    tags: list[str] = Field(default_factory=list)
    voice: VoiceAnchor = Field(default_factory=VoiceAnchor)
    image: ImagePromptTemplate | None = None
    images: list[CharacterImage] = Field(default_factory=list)
    structural_relationships: list[StructuralRelationship] = Field(default_factory=list)
    description: str = ""
    body: str = ""
    household_id: str | None = None
    privacy: CharacterPrivacy = Field(default_factory=CharacterPrivacy)


class ResolvedCharacter(BaseModel):
    """Character after the cascade has been applied, with state and capabilities."""

    character: Character
    current_state: CharacterState
    capabilities: list[Json] = Field(default_factory=list)  # Capability at runtime
    source_chain: list[Json] = Field(default_factory=list)  # ResolutionSource at runtime
    overrides_applied: list[str] = Field(default_factory=list)


class PCEntry(BaseModel):
    character_ref: CharacterRef
    name: str
    owner: str  # 'local' in v1; account id in v2
    active: bool = True
    # Rich switcher payload (frontend spec §8). All optional; the switcher
    # falls back to a bare label when these are missing.
    current_scene_id: str | None = None
    current_location_ref: str | None = None
    last_played_at: datetime | None = None


class CharacterFilter(BaseModel):
    roles: list[CharacterRole] | None = None
    tags: list[str] | None = None
    world_ids: list[str] | None = None
    name_contains: str | None = None


class AwarenessState(StrEnum):
    UNKNOWN = "unknown"
    AWARE = "aware"
    INTIMATE = "intimate"
    ESTRANGED = "estranged"


class RelationshipState(BaseModel):
    affection: int = 0
    trust: int = 0
    dominance: int = 0
    intimacy: int = 0
    awareness: AwarenessState = AwarenessState.UNKNOWN
    custom: Json = Field(default_factory=dict)


class RelationshipEvent(BaseModel):
    in_post: str | None
    summary: str
    delta: Json = Field(default_factory=dict)
    at: str | None = None
    """ISO-8601 UTC timestamp recorded when the event was appended."""


class DriftReport(BaseModel):
    character_ref: CharacterRef
    window: int
    drift_score: float
    evidence: list[str] = Field(default_factory=list)
    corrective_context: str = ""


class CapsuleDraft(BaseModel):
    """Auto-drafted capsule fields for a sparse emergent character.

    Returned by the ``LLMCapsuleDrafter`` hook wired into
    :class:`CharactersService` and applied back through
    ``update_emergent`` so the standard persistence path handles it
    (spec 2026-05-17 §10).
    """

    summary_line: str = ""
    tags: list[str] = Field(default_factory=list)


class PromotionProposal(BaseModel):
    """Preview of what :meth:`CharactersService.promote_to_library` would write.

    Returned by ``propose_promotion``; the UI shows this to the user, who then
    confirms by calling ``promote_to_library(..., confirm=True)``. Warnings
    flag conditions that should block an automatic commit (id collision in
    the target world, missing voice anchor, missing description, etc.).
    """

    campaign_id: str
    character_id: str
    target_world_id: str
    target_library_id: str
    target_path: str
    frontmatter: Json = Field(default_factory=dict)
    body: str = ""
    warnings: list[str] = Field(default_factory=list)


class ImportResult(BaseModel):
    created: list[str] = Field(default_factory=list)
    updated: list[str] = Field(default_factory=list)
    skipped: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


class IngestOptions(BaseModel):
    """Knobs for the Character Card V2/V3 ingestor.

    The ingestor is deterministic by default. Each ``parse_*`` toggle keeps
    the parse pure / regex-based; the ``enrich_with_llm`` toggle is the only
    one that calls out to a language model and requires the caller to wire a
    callable through ``CharactersService``.
    """

    extract_relationships: bool = True
    """Run the deterministic relationship/faction extractor over the body."""

    keep_embedded_avatar: bool = True
    """Save the embedded PNG (if any) as a portrait in ``images``."""

    derive_image_prompt: bool = True
    """Synthesize an ``ImagePromptTemplate.base_prompt`` from the description."""

    role_default: CharacterRole = CharacterRole.MAJOR_NPC
    """Role to assign when the card does not specify one."""

    enrich_with_llm: bool = False
    """If true, call the injected LLM to refine voice anchors + tags."""

    llm_task: str = "character_ingest"
    """Routing key passed to the LLM gateway when ``enrich_with_llm`` is on."""

    world_factions: list[str] = Field(default_factory=list)
    """Known faction slugs to match against when extracting affiliations."""

    world_characters: list[str] = Field(default_factory=list)
    """Known character slugs for cross-linking structural relationships."""

    avatar_dir: str | None = None
    """Optional override for where embedded avatars should be written."""


class IngestedCharacterCard(BaseModel):
    """Result of ingesting a Character Card V2/V3 payload.

    Bundles the projected :class:`CharacterData` ready to write, the raw
    decoded fields for callers that want to display them verbatim (creator
    notes, alternate greetings, character book), the embedded avatar bytes
    when present, and any warnings produced during parsing.
    """

    data: CharacterData
    spec: str = ""  # 'chara_card_v2' / 'chara_card_v3' / 'unknown'
    spec_version: str = ""
    creator: str = ""
    creator_notes: str = ""
    character_version: str = ""
    system_prompt: str = ""
    post_history_instructions: str = ""
    alternate_greetings: list[str] = Field(default_factory=list)
    character_book: Json = Field(default_factory=dict)
    extensions: Json = Field(default_factory=dict)
    avatar_bytes: bytes | None = None
    avatar_mime: str = ""
    warnings: list[str] = Field(default_factory=list)

    model_config = {"arbitrary_types_allowed": True}
