"""Guard: the lint ratchets stay honest.

`scripts/ratchet.py` is what lets three gates -- ruff's wider selection, mypy,
and the type-checked half of typescript-eslint -- land blocking against a tree
that has thousands of findings. Everything it promises rests on two things
being true: the comparison has to fail in *both* directions (new findings, and
findings the baseline still claims), and the baselines have to be a canonical
rendering of what the tools actually said, not a hand-edited file that drifted.

The comparison is tested directly. The baselines are tested for shape rather
than content: running ruff, mypy and eslint from inside pytest would triple the
suite's runtime and make it depend on `frontend/node_modules`, which is the
`check-*` targets' job. What is checked here is everything that can go wrong
*without* running them -- a path that no longer exists, a count that is zero or
negative, a file reflowed by hand, a baseline for a tool that no longer has a
collector.
"""

from __future__ import annotations

import collections
import json
import pathlib
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))

import ratchet  # noqa: E402 -- the sys.path line above is what makes it importable

BASELINES = sorted(ratchet.BASELINES.glob("*.json"))


# ------------------------------------------------------------ the comparison

def _counter(pairs) -> collections.Counter:
    return collections.Counter(dict(pairs))


def test_matching_counts_are_silent():
    same = _counter([(("a.py", "F401"), 3)])
    assert ratchet.compare(same, same) == ([], [])


def test_a_new_finding_is_a_regression():
    regressions, improvements = ratchet.compare(
        _counter([(("a.py", "F401"), 4)]), _counter([(("a.py", "F401"), 3)])
    )
    assert improvements == []
    assert len(regressions) == 1 and "3 -> 4" in regressions[0]


def test_a_first_finding_in_an_unlisted_file_is_a_regression():
    """The case the whole design turns on: a file with no baseline entry is
    held to the full rule set, so new code never inherits the backlog."""
    regressions, _ = ratchet.compare(
        _counter([(("new.py", "B904"), 1)]), collections.Counter()
    )
    assert len(regressions) == 1 and "new.py" in regressions[0]


def test_a_fixed_finding_is_also_a_failure():
    """This is what makes it a ratchet rather than a licence. If an
    improvement passed silently the baseline would only ever be regenerated by
    someone who happened to feel like it, and the recorded numbers would drift
    upward of the real ones until they permitted anything."""
    _, improvements = ratchet.compare(
        _counter([(("a.py", "F401"), 1)]), _counter([(("a.py", "F401"), 3)])
    )
    assert len(improvements) == 1 and "3 -> 1" in improvements[0]


def test_an_emptied_file_is_reported_by_name():
    """A file the tool no longer reports at all still has to surface: it is the
    most common improvement, and `found` has no key for it."""
    _, improvements = ratchet.compare(
        collections.Counter(), _counter([(("gone.py", "F401"), 2)])
    )
    assert len(improvements) == 1 and "gone.py" in improvements[0]


def test_rules_are_compared_separately_within_a_file():
    """Keyed by (file, rule), not by file. A module carrying 85 `B904`s must
    still fail on its first new `F401` -- which a per-file total would net out
    against any `B904` fixed in the same change."""
    regressions, improvements = ratchet.compare(
        _counter([(("a.py", "B904"), 84), (("a.py", "F401"), 1)]),
        _counter([(("a.py", "B904"), 85)]),
    )
    assert len(regressions) == 1 and "F401" in regressions[0]
    assert len(improvements) == 1 and "B904" in improvements[0]


# ------------------------------------------------------------- serialization

def test_round_trip_is_exact():
    found = _counter([(("b.py", "E402"), 1), (("a.py", "F401"), 2), (("a.py", "B904"), 1)])
    assert ratchet.loads(ratchet.dumps(found)) == found


def test_serialization_is_ordered():
    """`--update` has to be idempotent for the "run make baseline and commit
    it" instruction to produce a reviewable diff rather than a reshuffle."""
    text = ratchet.dumps(_counter([(("b.py", "F401"), 1), (("a.py", "Z9"), 1), (("a.py", "A1"), 1)]))
    assert list(json.loads(text)) == ["a.py", "b.py"]
    assert list(json.loads(text)["a.py"]) == ["A1", "Z9"]


# ---------------------------------------------------------- the baseline files

def test_there_is_a_baseline_for_every_tool():
    assert {p.stem for p in BASELINES} == set(ratchet.COLLECTORS)


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_baseline_is_canonically_serialized(path: pathlib.Path):
    """Byte-for-byte what `--update` writes. A hand edit that adds an entry
    (rather than fixing the code) is the failure mode this catches: it lands as
    a reflow of the whole file, in a diff a reviewer cannot skim past."""
    text = path.read_text(encoding="utf-8")
    assert ratchet.dumps(ratchet.loads(text)) == text, (
        f"{path.name} is not what `make baseline` would write. Regenerate it."
    )


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_baseline_counts_are_positive(path: pathlib.Path):
    zero = [k for k, v in ratchet.loads(path.read_text(encoding="utf-8")).items() if v < 1]
    assert not zero, f"{path.name} records non-findings, which permit one each: {zero}"


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_every_baselined_file_still_exists(path: pathlib.Path):
    """A renamed or deleted file leaves an entry that permits findings in a
    path nothing can produce -- harmless, but it is also how a baseline stops
    being a list of real work and becomes archaeology."""
    missing = sorted({f for f, _ in ratchet.loads(path.read_text(encoding="utf-8"))
                      if not (REPO / f).exists()})
    assert not missing, f"{path.name} names files that are not in the tree: {missing}"
