"""Guard: the lint ratchets stay honest.

`scripts/ratchet.py` is what lets three gates -- ruff's wider selection, mypy,
and the type-checked half of typescript-eslint -- land blocking against a tree
that has thousands of findings. Everything it promises rests on two things
being true: the comparison has to fail in *both* directions (new findings, and
findings the baseline still claims), and the baselines have to be a canonical
rendering of what the tools actually said, not a hand-edited file that drifted.

The comparison is tested directly. The baselines are tested for shape rather
than content: running ruff, mypy and eslint from inside pytest would triple the
suite's runtime and make it depend on `frontend/node_modules`, which is the
`check-*` targets' job. What is checked here is everything that can go wrong
*without* running them -- a path that no longer exists, a count that is zero or
negative, a file reflowed by hand, a baseline for a tool that no longer has a
collector.
"""

from __future__ import annotations

import collections
import json
import pathlib
import re
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))

import ratchet  # noqa: E402 -- the sys.path line above is what makes it importable

BASELINES = sorted(ratchet.BASELINES.glob("*.json"))


# ------------------------------------------------------------ the comparison

def _counter(pairs) -> collections.Counter:
    return collections.Counter(dict(pairs))


def test_matching_counts_are_silent():
    same = _counter([(("a.py", "F401"), 3)])
    assert ratchet.compare(same, same) == ([], [])


def test_a_new_finding_is_a_regression():
    regressions, improvements = ratchet.compare(
        _counter([(("a.py", "F401"), 4)]), _counter([(("a.py", "F401"), 3)])
    )
    assert improvements == []
    assert len(regressions) == 1 and "3 -> 4" in regressions[0]


def test_a_first_finding_in_an_unlisted_file_is_a_regression():
    """The case the whole design turns on: a file with no baseline entry is
    held to the full rule set, so new code never inherits the backlog."""
    regressions, _ = ratchet.compare(
        _counter([(("new.py", "B904"), 1)]), collections.Counter()
    )
    assert len(regressions) == 1 and "new.py" in regressions[0]


def test_a_fixed_finding_is_also_a_failure():
    """This is what makes it a ratchet rather than a licence. If an
    improvement passed silently the baseline would only ever be regenerated by
    someone who happened to feel like it, and the recorded numbers would drift
    upward of the real ones until they permitted anything."""
    _, improvements = ratchet.compare(
        _counter([(("a.py", "F401"), 1)]), _counter([(("a.py", "F401"), 3)])
    )
    assert len(improvements) == 1 and "3 -> 1" in improvements[0]


def test_an_emptied_file_is_reported_by_name():
    """A file the tool no longer reports at all still has to surface: it is the
    most common improvement, and `found` has no key for it."""
    _, improvements = ratchet.compare(
        collections.Counter(), _counter([(("gone.py", "F401"), 2)])
    )
    assert len(improvements) == 1 and "gone.py" in improvements[0]


def test_rules_are_compared_separately_within_a_file():
    """Keyed by (file, rule), not by file. A module carrying 85 `B904`s must
    still fail on its first new `F401` -- which a per-file total would net out
    against any `B904` fixed in the same change."""
    regressions, improvements = ratchet.compare(
        _counter([(("a.py", "B904"), 84), (("a.py", "F401"), 1)]),
        _counter([(("a.py", "B904"), 85)]),
    )
    assert len(regressions) == 1 and "F401" in regressions[0]
    assert len(improvements) == 1 and "B904" in improvements[0]


# ------------------------------------------------------------- serialization

def test_round_trip_is_exact():
    found = _counter([(("b.py", "E402"), 1), (("a.py", "F401"), 2), (("a.py", "B904"), 1)])
    assert ratchet.loads(ratchet.dumps(found)) == found


def test_serialization_is_ordered():
    """`--update` has to be idempotent for the "run make baseline and commit
    it" instruction to produce a reviewable diff rather than a reshuffle."""
    text = ratchet.dumps(_counter([(("b.py", "F401"), 1), (("a.py", "Z9"), 1), (("a.py", "A1"), 1)]))
    assert list(json.loads(text)) == ["a.py", "b.py"]
    assert list(json.loads(text)["a.py"]) == ["A1", "Z9"]


# ---------------------------------------------------------- the baseline files

def test_there_is_a_baseline_for_every_tool():
    assert {p.stem for p in BASELINES} == set(ratchet.COLLECTORS)


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_baseline_is_canonically_serialized(path: pathlib.Path):
    """Byte-for-byte what `--update` writes. A hand edit that adds an entry
    (rather than fixing the code) is the failure mode this catches: it lands as
    a reflow of the whole file, in a diff a reviewer cannot skim past."""
    text = path.read_text(encoding="utf-8")
    assert ratchet.dumps(ratchet.loads(text)) == text, (
        f"{path.name} is not what `make baseline` would write. Regenerate it."
    )


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_baseline_counts_are_positive(path: pathlib.Path):
    zero = [k for k, v in ratchet.loads(path.read_text(encoding="utf-8")).items() if v < 1]
    assert not zero, f"{path.name} records non-findings, which permit one each: {zero}"


@pytest.mark.parametrize("path", BASELINES, ids=lambda p: p.name)
def test_every_baselined_file_still_exists(path: pathlib.Path):
    """A renamed or deleted file leaves an entry that permits findings in a
    path nothing can produce -- harmless, but it is also how a baseline stops
    being a list of real work and becomes archaeology."""
    missing = sorted({f for f, _ in ratchet.loads(path.read_text(encoding="utf-8"))
                      if not (REPO / f).exists()})
    assert not missing, f"{path.name} names files that are not in the tree: {missing}"


# ------------------------------------------------- the tool adapters
#
# The parsers are where a tool upgrade breaks this quietly, and where the
# difference between "found nothing" and "did not run" lives. Each is driven
# against canned output rather than the real tool: running ruff, mypy and
# eslint from inside pytest would triple the suite and make it depend on
# `frontend/node_modules`, which is what the `check-*` targets are for.


@pytest.fixture
def canned(monkeypatch):
    """Replace the subprocess layer with a scripted reply per invocation."""

    def install(*outputs: str):
        replies = list(outputs)

        def fake_run(argv, cwd, ok_codes):
            return replies.pop(0)

        monkeypatch.setattr(ratchet, "_run", fake_run)

    return install


#: What `_require_version` sees; the real pins live in backend/pyproject.toml.
RUFF_V = f"ruff {ratchet._pin('ruff')}\n"
MYPY_V = f"mypy {ratchet._pin('mypy')} (compiled: yes)\n"


def test_the_pins_are_readable():
    """`_require_version` is only as good as the pin it reads. If the `dev`
    extra ever stops pinning exactly, this says so here rather than as a
    confusing mid-gate failure."""
    assert re.fullmatch(r"[\d.]+", ratchet._pin("ruff"))
    assert re.fullmatch(r"[\d.]+", ratchet._pin("mypy"))


def test_a_version_that_merely_contains_the_pin_is_refused(canned):
    """The sloppy form of this check was `pin in output`, which passes for a
    ruff 10.16.0 that has nothing to do with the pinned 0.16.0."""
    canned(f"ruff 1{ratchet._pin('ruff')}\n")
    with pytest.raises(ratchet.ToolError, match="baselines were built with"):
        ratchet.collect_ruff()


def test_a_different_tool_version_is_refused(canned):
    """The failure this prevents: a contributor regenerates a baseline with
    the ruff they happen to have, and CI -- on the pinned one -- reports a
    different count for reasons no diff explains."""
    canned("ruff 0.0.1\n")
    with pytest.raises(ratchet.ToolError, match="baselines were built with"):
        ratchet.collect_ruff()


def test_ruff_findings_are_counted_per_file_and_rule(canned):
    canned(RUFF_V, json.dumps([
        {"filename": str(REPO / "a.py"), "code": "F401", "message": "x"},
        {"filename": str(REPO / "a.py"), "code": "F401", "message": "y"},
        {"filename": str(REPO / "b.py"), "code": "B904", "message": "z"},
    ]))
    assert ratchet.collect_ruff() == _counter(
        [(("a.py", "F401"), 2), (("b.py", "B904"), 1)]
    )


def test_a_ruff_finding_with_no_rule_is_not_ratchetable(canned):
    """ruff reports a syntax error with a null code. Counting it under some
    stand-in would let a file that does not parse sit in the baseline."""
    canned(RUFF_V, json.dumps([
        {"filename": str(REPO / "a.py"), "code": None, "message": "SyntaxError"},
    ]))
    with pytest.raises(ratchet.ToolError, match="unattributed"):
        ratchet.collect_ruff()


def test_output_that_is_not_json_is_a_broken_tool(canned):
    """npx prints its own diagnostics on stdout and exits 1 when the binary is
    missing -- indistinguishable, to the exit code, from "found violations"."""
    canned(RUFF_V, "npm error could not determine executable to run\n")
    with pytest.raises(ratchet.ToolError, match="did not print JSON"):
        ratchet.collect_ruff()


def test_mypy_errors_are_counted_and_notes_are_not(canned):
    canned(MYPY_V, (
        "backend/src/grimoire/a.py:12: error: Incompatible types  [assignment]\n"
        "backend/src/grimoire/a.py:12: note: Left operand is of type X\n"
        "backend/src/grimoire/a.py:99:4: error: Missing return  [return]\n"
    ))
    assert ratchet.collect_mypy() == _counter([
        (("backend/src/grimoire/a.py", "assignment"), 1),
        (("backend/src/grimoire/a.py", "return"), 1),
    ])


def test_a_mypy_error_without_a_code_stops_the_gate(canned):
    """It cannot be keyed, so it would drop out of the comparison entirely --
    a real error the ratchet reported as an improvement."""
    canned(MYPY_V, "backend/src/grimoire/a.py:1: error: something went wrong")
    with pytest.raises(ratchet.ToolError, match="no error code"):
        ratchet.collect_mypy()


def _eslint(*files):
    return json.dumps([{"filePath": str(REPO / "frontend" / p), "messages": list(m)}
                       for p, m in files])


def test_eslint_findings_are_counted_per_rule(canned, monkeypatch):
    monkeypatch.setattr(ratchet, "_node_modules_present", lambda: True)
    canned(_eslint(("src/a.tsx", [
        {"ruleId": "react/jsx-key", "message": "k"},
        {"ruleId": "react/jsx-key", "message": "k"},
        {"ruleId": "jsx-a11y/no-autofocus", "message": "a"},
    ])))
    assert ratchet.collect_eslint() == _counter([
        (("frontend/src/a.tsx", "react/jsx-key"), 2),
        (("frontend/src/a.tsx", "jsx-a11y/no-autofocus"), 1),
    ])


def test_an_unused_disable_directive_ratchets_like_a_finding(canned, monkeypatch):
    """eslint reports it with no rule id, because the rule it names is exactly
    the one that found nothing. Crashing on that would turn a stale
    suppression into an unreadable harness error."""
    monkeypatch.setattr(ratchet, "_node_modules_present", lambda: True)
    canned(_eslint(("src/a.tsx", [{"ruleId": None, "message": "Unused eslint-disable"}])))
    assert ratchet.collect_eslint() == _counter(
        [(("frontend/src/a.tsx", ratchet.UNUSED_DISABLE), 1)]
    )


def test_a_file_eslint_could_not_parse_stops_the_gate(canned, monkeypatch):
    """Its zero findings are not evidence that it has none."""
    monkeypatch.setattr(ratchet, "_node_modules_present", lambda: True)
    canned(_eslint(("src/a.tsx", [{"ruleId": None, "fatal": True, "message": "Parsing error"}])))
    with pytest.raises(ratchet.ToolError, match="could not parse"):
        ratchet.collect_eslint()


# ---------------------------------------------------------------- --update

def test_update_will_not_write_a_bigger_baseline(monkeypatch, tmp_path):
    """The half that makes "ratchet" true. Regenerating has to be the way an
    improvement is recorded, not the way a regression is accepted."""
    monkeypatch.setattr(ratchet, "BASELINES", tmp_path)
    (tmp_path / "ruff.json").write_text(ratchet.dumps(_counter([(("a.py", "F401"), 1)])))
    monkeypatch.setitem(ratchet.COLLECTORS, "ruff",
                        lambda: _counter([(("a.py", "F401"), 2)]))
    assert ratchet.update("ruff") == 1
    assert ratchet.loads((tmp_path / "ruff.json").read_text()) == _counter(
        [(("a.py", "F401"), 1)]
    ), "the baseline was rewritten despite the refusal"


def test_update_writes_a_smaller_baseline_without_ceremony(monkeypatch, tmp_path):
    monkeypatch.setattr(ratchet, "BASELINES", tmp_path)
    (tmp_path / "ruff.json").write_text(ratchet.dumps(_counter([(("a.py", "F401"), 3)])))
    monkeypatch.setitem(ratchet.COLLECTORS, "ruff",
                        lambda: _counter([(("a.py", "F401"), 1)]))
    assert ratchet.update("ruff") == 0
    assert ratchet.loads((tmp_path / "ruff.json").read_text()) == _counter(
        [(("a.py", "F401"), 1)]
    )


def test_accept_regressions_is_the_way_a_rename_lands(monkeypatch, tmp_path):
    monkeypatch.setattr(ratchet, "BASELINES", tmp_path)
    (tmp_path / "ruff.json").write_text(ratchet.dumps(_counter([(("old.py", "F401"), 1)])))
    monkeypatch.setitem(ratchet.COLLECTORS, "ruff",
                        lambda: _counter([(("new.py", "F401"), 1)]))
    assert ratchet.update("ruff", accept_regressions=True) == 0
    assert ratchet.loads((tmp_path / "ruff.json").read_text()) == _counter(
        [(("new.py", "F401"), 1)]
    )


def test_accept_regressions_alone_is_an_argument_error():
    """It only means anything with --update, and silently doing a check
    instead would be the worst of both."""
    with pytest.raises(SystemExit):
        ratchet.main(["ruff", "--accept-regressions"])
