"""Roll of Years: DR year -> named year. Generated from the Forgotten
Realms wiki (scrape_roll_of_years.py, 2026-07-05); do not hand-edit."""

YEAR_NAMES: dict[int, str] = {
    1: 'Year of Sunrise',
    2: 'Year of the Smiling Hag',
    3: 'Year of the Faded Flower',
    4: 'Year of the Slaked Blade',
    5: 'Year of the Clutched Emerald',
    6: 'Year of the Firestars',
    7: "Year of the Vampires' Sun",
    8: 'Year of Spellspheres',
    9: 'Year of the Falling Wall',
    10: 'Year of Dreams',
    11: 'Year of the Mellifluent Sphinx',
    12: 'Year of Wistful Looks',
    13: 'Year of the Sweet Songs',
    14: 'Year of the Unknown Beloved',
    15: 'Year of Glittering Glory',
    16: 'Year of Distant Thunder',
    17: 'Year of Crashing Glee',
    18: 'Year of the Lasting Wonders',
    19: 'Year of the Blessed Beast',
    20: 'Year of the Fallen Fury',
    21: 'Year of Lamenting',
    22: 'Year of the Empty Fist',
    23: 'Year of Falling Arrows',
    24: 'Year of the Evasive Hare',
    25: 'Year of Many Runes',
    26: 'Year of Opening Doors',
    27: 'Year of Shadowed Blades',
    28: 'Year of the Barren Fields',
    29: 'Year of Carved Cliffs',
    30: 'Year of the Crushed Monument',
    31: 'Year of the Garrulous Gargoyle',
    32: 'Year of Errant Arrows',
    33: 'Year of Slowing Sands',
    34: 'Year of Purloined Power',
    35: 'Year of Scaled Lightning',
    36: 'Year of Consuming Ice',
    37: 'Year of Dark Venom',
    38: 'Year of Verdant Pain',
    39: 'Year of Proud Flame',
    40: 'Year of the Gaunt Wolf',
    41: 'Year of the Branded Lily',
    42: 'Year of the Charging Cavalry',
    43: 'Year of Frostbrands',
    44: 'Year of the Vow Manifest',
    45: 'Year of the Torpid Arms',
    46: 'Year of the Hidden Fortress',
    47: 'Year of the Crystal Orb',
    48: 'Year of the Bloodied Pikes',
    49: 'Year of the Deadly Joust',
    50: 'Year of the Barbed Wind',
    51: 'Year of the Red Pearls',
    52: 'Year of the Thundering Horde',
    53: 'Year of the Desert Kingdoms',
    54: 'Year of the Forlorn Prince',
    55: 'Year of the Caustic Blood',
    56: 'Year of the Laughing Nightmare',
    57: 'Year of Lamplit Nights',
    58: 'Year of the Dazzling Dolphins',
    59: 'Year of the Tangled Threads',
    60: "Year of the Pirate's Lost Eye",
    61: 'Year of the Branded Mage',
    62: 'Year of the Lonely Daughters',
    63: 'Year of the Winsome Trio',
    64: 'Year of the Boisterous Orc',
    65: 'Year of the Foaming Wave',
    66: 'Year of the Spellbound Heir',
    67: 'Year of the Redolent Innkeeper',
    68: 'Year of the Echoing Chasm',
    69: 'Year of the Lit Pathway',
    70: 'Year of the Mournful Dance',
    71: 'Year of the Entwined Sculpture',
    72: "Year of the Climber's Rest",
    73: 'Year of Wise Counsel',
    74: 'Year of the Fearful Mercenary',
    75: 'Year of the Clinging Death',
    76: 'Year of Windsong',
    77: 'Year of the Quivering Mountains',
    78: 'Year of the Closing Darkness',
    79: 'Year of the Whispering Woods',
    80: 'Year of the Mordant Blight',
    81: 'Year of the Vampiric Torch',
    82: 'Year of the Preordained Youth',
    83: "Year of the Satyr's Adulation",
    84: 'Year of the Monotonous Speech',
    85: 'Year of the Orb Obsidious',
    86: 'Year of the Eyeless Wraith',
    87: 'Year of the Hoar Frost',
    88: 'Year of the Mortified Monk',
    89: 'Year of the Faithful Oracle',
    90: 'Year of the Moor Birds',
    91: 'Year of the Scabbard Peace',
    92: 'Year of the Vanished Tattoo',
    93: 'Year of the Quiet Valley',
    94: 'Year of the Multitudes',
    95: 'Year of the Reluctant Hero',
    96: 'Year of the Mournful Harp',
    97: 'Year of Flickering Nyths',
    98: 'Year of Revealed Grimoires',
    99: 'Year of the Dragonstar',
    100: 'Year of Greybeards',
    101: 'Year of the Smiling Moon',
    102: 'Year of the Ormage',
    103: 'Year of the White Hound',
    104: 'Year of the Preying Griffon',
    105: 'Year of the Tattooed Mistress',
    106: 'Year of the Adamantine Spiral',
    107: 'Year of the Fledglings',
    108: 'Year of the Flood',
    109: 'Year of the False Ghost',
    110: 'Year of the Quirt',
    111: 'Year of Fallen Guards',
    112: 'Year of the Tusk',
    113: 'Year of the Belching Boggle',
    114: 'Year of the Jagged Leaves',
    115: 'Year of the Morning Glory',
    116: 'Year of the Mortal Promise',
    117: 'Year of the Swinging Pendulum',
    118: 'Year of the Monkey',
    119: "Year of the Mountain's Fire",
    120: 'Year of the Remembered Pain',
    121: 'Year of the Embroidered Button',
    122: 'Year of the Mourning Armsmen',
    123: 'Year of the Icy Axe',
    124: 'Year of the Biting Frost',
    125: 'Year of the Ironwood',
    126: 'Year of the Cinnamon Haze',
    127: 'Year of the Defiant Stone',
    128: 'Year of the Addled Arcanist',
    129: "Year of the Mummy's Amulet",
    130: 'Year of the Dwarven Twins',
    131: "Year of the Cockatrice's Stare",
    132: 'Year of Thirteen Prides Lost',
    133: 'Year of the Arduous Journey',
    134: 'Year of the Impassable Chasm',
    135: "Year of the Halfling's Dale",
    136: 'Year of the Stalking Beholders',
    137: "Year of the King's Destiny",
    138: 'Year of Sparks Flying',
    139: 'Year of the Resolute Courtesans',
    140: 'Year of the Executioner',
    141: 'Year of the Impenetrable Mystery',
    142: 'Year of the Prowling Naga',
    143: 'Year of the Smiling Princess',
    144: 'Year of the Fear and Flame',
    145: "Year of the Pirates' Port",
    146: 'Year of the Risen Towers',
    147: 'Year of the Iron Colossus',
    148: 'Year of the Blue Ice',
    149: 'Year of the Dwarf',
    150: 'Year of the Lost Library',
    151: 'Year of the Kraken',
    152: 'Year of the Severed Hand',
    153: 'Year of the Wolfstone',
    154: 'Year of the Jealous Hag',
    155: 'Year of the Mellifluous Heaps',
    156: 'Year of the Imaginary Foe',
    157: 'Year of the Resounding Call',
    158: 'Year of the Imploring Widow',
    159: 'Year of the Lost Profit',
    160: 'Year of the Smirking Knaves',
    161: "Year of the Hangman's Noose",
    162: 'Year of the Great Dwarven Gate',
    163: 'Year of the Screeching Vole',
    164: 'Year of the Fallen Temple',
    165: 'Year of the Smoking Brazier',
    166: 'Year of the Reremouse',
    167: 'Year of the Deep Wellspring',
    168: 'Year of Scattered Stars',
    169: 'Year of the Weary Warrior',
    170: 'Year of the Bloodties',
    171: 'Year of Unkind Weapons',
    172: 'Year of the Great Debate',
    173: 'Year of Screaming Sharn',
    174: 'Year of the Windswept Plains',
    175: 'Year of the Black Boats',
    176: 'Year of the Wyrmclaws',
    177: 'Year of the Troublesome Vixen',
    178: 'Year of the Jealous Spouse',
    179: 'Year of the Engraved Locket',
    180: 'Year of Leaning Pillars',
    181: 'Year of the Sinking Islands',
    182: 'Year of the Quenched Stirges',
    183: 'Year of the Murmuring Dead',
    184: 'Year of the Leucrotta',
    185: 'Year of the Golden Elephant',
    186: 'Year of Vestigial Wings',
    187: 'Year of the Twisted Tree',
    188: 'Year of Dissolute Drow',
    189: 'Year of the Cowled Defender',
    190: 'Year of the Apparition',
    191: 'Year of the Broken Lands',
    192: 'Year of the Magnificent Equine',
    193: 'Year of the Raised Brow',
    194: 'Year of Coiling Smoke',
    195: 'Year of the Yeti',
    196: 'Year of Yearning Elves',
    197: 'Year of the Unseeing Priest',
    198: 'Year of the Almond Eyes',
    199: 'Year of the Cold Enchanter',
    200: 'Year of Leaping Flames',
    201: 'Year of the Student',
    202: 'Year of the Fanged Gauntlet',
    203: 'Year of Scattered Sands',
    204: 'Year of the Avarice',
    205: 'Year of the Greengrass',
    206: 'Year of the Regal Doppelganger',
    207: 'Year of the Majestic Mace',
    208: 'Year of Riven Realms',
    209: 'Year of the Dying Eye',
    210: 'Year of the Steelfall',
    211: 'Year of Spoiled Splendors',
    212: 'Year of the Awakening Magic',
    213: 'Year of the Waking Wraith',
    214: 'Year of Lost Voices',
    215: 'Year of the Shadowsnare',
    216: 'Year of the Battle Horns',
    217: 'Year of the Giant Skulls',
    218: 'Year of the Dancing Lights',
    219: 'Year of Old Danger',
    220: 'Year of the Sword Violets',
    221: 'Year of the Melting Manscorpion',
    222: 'Year of the Ghosthunt',
    223: 'Year of Dark Dreams',
    224: 'Year of the Flaming Forests',
    225: 'Year of the Shattered Skulls',
    226: 'Year of the Empty Turret',
    227: 'Year of the Raised Banner',
    228: 'Year of the Loremasters',
    229: 'Year of the Black Flame',
    230: 'Year of the Wailing Dryads',
    231: 'Year of the Mist Dragon',
    232: 'Year of the Leaping Centaur',
    233: 'Year of Much Ale',
    234: 'Year of Bloodflowers',
    235: 'Year of Drawn Knives',
    236: 'Year of the Plague Clouds',
    237: 'Year of the Disappearing Dragon',
    238: 'Year of Many Mushrooms',
    239: 'Year of the Wandering Leucrotta',
    240: 'Year of the Chosen',
    241: "Year of the Hippogriff's Folly",
    242: 'Year of the Hunting Horn',
    243: 'Year of the Sad Orm',
    244: 'Year of the Elfsands',
    245: 'Year of the Dun Dragon',
    246: 'Year of the Sepulchre',
    247: 'Year of the Moaning Maiden',
    248: 'Year of Tumbletowns',
    249: 'Year of the Crystal Casket',
    250: 'Year of the Storm Crown',
    251: 'Year of the Strange Seedlings',
    252: 'Year of the Bloody Spider',
    253: 'Year of Somber Smiles',
    254: 'Year of the Ghost Horse',
    255: 'Year of the Magethunder',
    256: 'Year of the Thousand Snows',
    257: 'Year of the Speaking Mountain',
    258: 'Year of the War Wyvern',
    259: 'Year of the Magedirge',
    260: 'Year of Sunless Stones',
    261: 'Year of Soaring Stars',
    262: 'Year of Pages Perilous',
    263: 'Year of the Worn Pages',
    264: 'Year of the Vanishing Cat',
    265: 'Year of the Masterful Plan',
    266: 'Year of the Unspoken Name',
    267: "Year of Bane's Shadow",
    268: 'Year of the Cruel Storms',
    269: 'Year of the Wild Roses',
    270: 'Year of the Unheeded Warning',
    271: 'Year of the Port Stormed',
    272: 'Year of the Weeping Kingdom',
    273: 'Year of the Delighted Dwarves',
    274: 'Year of the Vested Vigil',
    275: 'Year of the Wrath Sword',
    276: 'Year of the Burnished Blade',
    277: 'Year of Broken Flame',
    278: 'Year of the Fallen Banner',
    279: 'Year of Smiling Nyth',
    280: 'Year of the Secreted Phylactery',
    281: 'Year of the Weeping Flail',
    282: 'Year of the Watchful Hermit',
    283: 'Year of the Skillful Tailor',
    284: 'Year of Fallen Flagons',
    285: 'Year of Wasteful Pride',
    286: 'Year of the Jolly Mongrels',
    287: 'Year of the Warped Narthex',
    288: "Year of the Xorn's Yearning",
    289: 'Year of the Waking Dreams',
    290: 'Year of Full Cribs',
    291: "Year of the Vintner's Dagger",
    292: 'Year of Frostfires',
    293: 'Year of Hounds',
    294: 'Year of the Yak Men',
    295: 'Year of the Wrathful Revenant',
    296: 'Year of the Two Riders',
    297: 'Year of the Wailing Mothers',
    298: 'Year of the Scarred Wagon',
    299: 'Year of the Vaasan Knot',
    300: 'Year of the Late Sun',
    301: 'Year of Argent Cape',
    302: 'Year of the Deep Bay',
    303: 'Year of the Crimson Tiara',
    304: 'Year of the Questing Raven',
    305: 'Year of the Barrows',
    306: 'Year of the Fanged Horde',
    307: 'Year of Sundered Sails',
    308: 'Year of Promise',
    309: 'Year of the Cascade',
    310: 'Year of the Amber Hulk',
    311: 'Year of the Lupine Embrace',
    312: 'Year of the Aurum Bramble',
    313: 'Year of Regretful Births',
    314: 'Year of the Stammering Apprentice',
    315: 'Year of the Carnivorose',
    316: 'Year of the Vibrant Land',
    317: 'Year of the Riven Shield',
    318: "Year of the Hero's Lament",
    319: 'Year of the Unforgotten Fire',
    320: 'Year of the Bright Plumage',
    321: 'Year of the Blessed Sleep',
    322: 'Year of Seven Scales',
    323: 'Year of the Miscast Shadow',
    324: "Year of Freedom's Friends",
    325: 'Year of the Silken Whisper',
    326: 'Year of Secret Slaughters',
    327: 'Year of the Sullen Grimalkin',
    328: 'Year of the Ermine Cloak',
    329: 'Year of the Closed Scroll',
    330: 'Year of Roused Giants',
    331: 'Year of the Cold Clashes',
    332: 'Year of the Crashing Steeple',
    333: 'Year of the Drawstring',
    334: 'Year of the Humbled Fiend',
    335: 'Year of Seven Stones',
    336: 'Year of the Whipped Cur',
    337: "Year of the Chosen's Blade",
    338: 'Year of the Envenomed Bolt',
    339: 'Year of the Vanished Foe',
    340: 'Year of the Uncrossed Bridge',
    341: 'Year of the Black Wing',
    342: 'Year of Cantobele Stalking',
    343: 'Year of Fraying Binds',
    344: 'Year of the Loom',
    345: 'Year of Flying Daggers',
    346: 'Year of Blushing Stars',
    347: "Year of the Sage's Fervor",
    348: 'Year of the Dagger',
    349: 'Year of the Toad',
    350: 'Year of the Hunter',
    351: 'Year of the Dancing Deer',
    352: 'Year of the Dancing Piper',
    353: 'Year of the Gold Band',
    354: 'Year of the Fleeting Pains',
    355: 'Year of Mourning Horns',
    356: 'Year of the Errant Kings',
    357: 'Year of the Pendulum',
    358: 'Year of the Battle Talons',
    359: 'Year of the Awakened Witch',
    360: 'Year of the Dusty Shelf',
    361: 'Year of the Fearless King',
    362: 'Year of the Greedy Altruist',
    363: 'Year of the Opal Key',
    364: 'Year of the Selfless Knave',
    365: 'Year of the Swift Sword',
    366: 'Year of the Molten Anvils',
    367: 'Year of the Shying Eyes',
    368: 'Year of the Bitter Smile',
    369: "Year of the Maiden's Fancy",
    370: 'Year of the Sleeping Dangers',
    371: 'Year of Emerald Eyes',
    372: 'Year of the Elder',
    373: 'Year of the Pacifist',
    374: 'Year of the Thoughtful Man',
    375: 'Year of the Woeful Resurrection',
    376: 'Year of the Leaping Hare',
    377: 'Year of the Ghoul',
    378: 'Year of Autumn Drums',
    379: 'Year of Seven Stars',
    380: 'Year of the Guarded Stance',
    381: 'Year of the Broken Chalice',
    382: 'Year of Steel Roses',
    383: 'Year of the Quelzarn',
    384: 'Year of Dreaming Dragons',
    385: "Year of the Lady's Gaze",
    386: 'Year of Dawn Moons',
    387: 'Year of the River Candles',
    388: 'Year of the Simoom',
    389: 'Year of the Wooded Altar',
    390: 'Year of the Half Moon',
    391: 'Year of the Azure Cockatrice',
    392: 'Year of the Firstborn',
    393: 'Year of the Dying Bard',
    394: "Year of the Herald's Tale",
    395: 'Year of the Narrow Escape',
    396: 'Year of the Purring Tiger',
    397: 'Year of the Swallowing Mists',
    398: 'Year of the Warning Ghost',
    399: 'Year of the Frayed Rope',
    400: 'Year of the Blue Shield',
    401: 'Year of the Serous Fist',
    402: 'Year of the Banished Bard',
    403: 'Year of the Stallion Triumphant',
    404: 'Year of Withered Flowers',
    405: 'Year of the Blinding Locusts',
    406: 'Year of the Catoblepas',
    407: 'Year of the Ebony Cudgel',
    408: 'Year of the Goblin King',
    409: 'Year of the Goblin King',
    410: 'Year of the Sun Crystal',
    411: 'Year of the Wavering Shadow',
    412: 'Year of the Burning Blazes',
    413: "Year of the Beholder's Grin",
    414: 'Year of Omen Stars',
    415: "Year of the Fiend's Kiss",
    416: 'Year of the Striped Moon',
    417: 'Year of the Brilliant Plan',
    418: "Year of the Eagle's Flight",
    419: 'Year of the Hale Blacksmith',
    420: 'Year of the Last Breath',
    421: 'Year of the Peerless Foe',
    422: 'Year of the Murderous Mire',
    423: 'Year of the Velvet Night',
    424: 'Year of the Ambitious Sycophant',
    425: 'Year of the Argent Shafts',
    426: 'Year of the Black Dawn',
    427: 'Year of Violet Fungi',
    428: "Year of the One's Tears",
    429: "Year of the Cat's Eye",
    430: 'Year of the Floating Rock',
    431: 'Year of the Hearth',
    432: 'Year of the Sea Princes',
    433: 'Year of the Rebellious Youth',
    434: 'Year of the Stallion Triumphant',
    435: 'Year of the Willing Sacrifice',
    436: 'Year of Steelscreaming',
    437: 'Year of Silver Holly',
    438: 'Year of the Bitter Root',
    439: "Year of the Child's Tear",
    440: 'Year of the Festering Heart',
    441: 'Year of the Haggling Merchant',
    442: "Year of the Relic's Vigil",
    443: 'Year of the Thousand Enemies',
    444: 'Year of the Infamous Wizard',
    445: 'Year of the Beardless Dwarf',
    446: 'Year of the Unblinking Eye',
    447: 'Year of the Awakening Treant',
    448: 'Year of the Haughty Friend',
    449: 'Year of Killing Ice',
    450: 'Year of the Corrie Fist',
    451: 'Year of Unleashed Fears',
    452: 'Year of the Rolling Heads',
    453: "Year of the Lady's Palace",
    454: 'Year of the Glorious Windfall',
    455: "Year of the Dryad's Dowry",
    456: 'Year of the Swift Hart',
    457: 'Year of the Unfurled Flag',
    458: "Year of the Beast's Redemption",
    459: 'Year of the Blooded Dagger',
    460: 'Year of Scorching Suns',
    461: 'Year of the Lissome Apprentice',
    462: 'Year of the Empty Helm',
    463: 'Year of the Burning Sands',
    464: 'Year of the Eclipsed Heart',
    465: 'Year of Dawn Blades',
    466: 'Year of the Burnt Spear',
    467: 'Year of the Four Winds',
    468: 'Year of the Bared Sword',
    469: 'Year of the Dusty Library',
    470: 'Year of the Merciful Shadow',
    471: 'Year of the Sundered Tower',
    472: 'Year of Full Cellars',
    473: 'Year of the Crowned Knave',
    474: 'Year of the Goblin Battles',
    475: "Year of the Maiden's Tears",
    476: 'Year of the Raging Hunter',
    477: 'Year of the Owlbear',
    478: 'Year of the Coarse Wool',
    479: 'Year of Forestsfrost',
    480: 'Year of the Winter Sphinx',
    481: 'Year of the Eversharp Axe',
    482: 'Year of the Blighted Vine',
    483: 'Year of the Soaring Galleon',
    484: 'Year of the Lawless Hunt',
    485: 'Year of the Arcane Image',
    486: 'Year of the Bleeding Altar',
    487: 'Year of Hidden Relics',
    488: 'Year of the Empty Hall',
    489: 'Year of the Foaming Tankard',
    490: "Year of the Crone's Counsel",
    491: 'Year of the Faltering Fires',
    492: 'Year of Azure Darkness',
    493: 'Year of the Ecstatic Priest',
    494: 'Year of the Ghost Ship',
    495: 'Year of the Listening Ear',
    496: 'Year of the Ravaging Dragon',
    497: 'Year of the Spear',
    498: 'Year of the Unstrung Harp',
    499: 'Year of the Wager',
    500: 'Year of the Flame Tongue',
    501: 'Year of the Lost Bird',
    502: 'Year of the Crawling Vine',
    503: 'Year of the Galloping Gorgon',
    504: 'Year of the Eclipsed Heart',
    505: 'Year of the Humble Knight',
    506: 'Year of the Opaque Eye',
    507: 'Year of the Rotting Pox',
    508: 'Year of the Stony Terror',
    509: 'Year of the Thunder Lizard',
    510: 'Year of the Unwavering Glare',
    511: 'Year of the Fortress Scoured',
    512: 'Year of the Wyvernfall',
    513: 'Year of the Blood Price',
    514: 'Year of the Elk',
    515: 'Year of the Frivolous Exchange',
    516: 'Year of the Haunting Hawk',
    517: 'Year of the Oaken Glade',
    518: 'Year of the Pendulous Tongues',
    519: 'Year of the Phoenix',
    520: 'Year of the Quiver',
    521: "Year of the Sea's Beauty",
    522: 'Year of the Unmasked Traitor',
    523: 'Year of Trials Arcane',
    524: 'Year of the Arcane Cabal',
    525: 'Year of the Cracked Bell',
    526: 'Year of the Besieged Keep',
    527: 'Year of Tatters',
    528: 'Year of the Burning Sky',
    529: 'Year of the Evening Tree',
    530: 'Year of the Gluttonous Otyugh',
    531: 'Year of the Lily',
    532: 'Year of the Perceptive Judge',
    533: 'Year of the Shattered Manacles',
    534: 'Year of the Spitting Viper',
    535: 'Year of the Upright Man',
    536: 'Year of the Laughing Lich',
    537: 'Year of the Basilisk',
    538: 'Year of the Amethyst Axe',
    539: 'Year of the Borrowed Crown',
    540: 'Year of the Colorful Costume',
    541: 'Year of the Etched Chevron',
    542: 'Year of the Grasping Claw',
    543: 'Year of the Lyre',
    544: 'Year of the Killing Rose',
    545: 'Year of the Pernicon',
    546: 'Year of the Rusted Sabre',
    547: 'Year of the Simpering Courtier',
    548: 'Year of the Eloene Bride',
    549: 'Year of the Unstoppable Ogre',
    550: 'Year of the Zealous',
    551: 'Year of the Barren Chamber',
    552: 'Year of the Dead',
    553: 'Year of the Gnashing Tooth',
    554: 'Year of the Waving Wheat',
    555: 'Year of the Dances Perilous',
    556: 'Year of the Green Man',
    557: 'Year of the Melding',
    558: 'Year of the Mithral Eagle',
    559: 'Year of the Scarlet Dagger',
    560: 'Year of the Unknown Truth',
    561: 'Year of the Three Setting Suns',
    562: 'Year of the Waking Feyr',
    563: 'Year of the Waking Feyr',
    564: 'Year of the Brandished Axe',
    565: 'Year of the Encrusted Pendant',
    566: 'Year of the Ghasts',
    567: 'Year of the Martyr',
    568: 'Year of the Pernicious Hauberk',
    569: 'Year of the Tumbled Bones',
    570: 'Year of Bright Fangs',
    571: 'Year of the Scholar',
    572: 'Year of Writhing Darkness',
    573: 'Year of the Sable Spider',
    574: 'Year of the Gored Griffon',
    575: 'Year of the Breaching Bulette',
    576: 'Year of the Sunless Passage',
    577: 'Year of the Alabaster Mounds',
    578: 'Year of the Floating Fish',
    579: 'Year of the Cultured Rake',
    580: 'Year of the Loose Coins',
    581: 'Year of the Harried Harpies',
    582: 'Year of the Deep Wound',
    583: 'Year of the Furled Sail',
    584: 'Year of the Juggernaut',
    585: 'Year of the Ogling Beholder',
    586: "Year of the Night's Dying",
    587: 'Year of Radiant Rods',
    588: 'Year of the Dragons Dawning',
    589: 'Year of the Splintered Oak',
    590: 'Year of the Turning Leaf',
    591: 'Year of Silver Streams',
    592: 'Year of the Supreme Duelist',
    593: 'Year of the Yellow Locus',
    594: 'Year of the Couched Spear',
    595: 'Year of the Coven',
    596: 'Year of the Flightless Eagle',
    597: 'Year of the Hungry Anelace',
    598: 'Year of the Pauper',
    599: 'Year of the Scourged Fool',
    600: 'Year of Fire and Frost',
    601: 'Year of the Desolate Warrior',
    602: 'Year of the Glimmering Sea',
    603: 'Year of Frigid Ghosts',
    604: 'Year of the Immured Imp',
    605: 'Year of Many Serpents',
    606: 'Year of the Kindly Lich',
    607: 'Year of the Crystal Vambrace',
    608: 'Year of Failed Daggers',
    609: 'Year of Old Bones',
    610: 'Year of the Spellfire',
    611: 'Year of the Normiir',
    612: "Year of the Jester's Smile",
    613: 'Year of the Glaring Eye',
    614: 'Year of the Shattered Scepter',
    615: "Year of the Lamia's Kiss",
    616: 'Year of the Ensorcelled Kings',
    617: 'Year of the Needless Slaughter',
    618: 'Year of the Siege Tower',
    619: 'Year of Orcsfall',
    620: 'Year of the Mountain Crypts',
    621: 'Year of the Nineteen Swords',
    622: 'Year of Soaring Shadows',
    623: 'Year of the Nightsilver',
    624: 'Year of the Journey Home',
    625: 'Year of the Torrents',
    626: 'Year of the Eagle and the Falcon',
    627: 'Year of the Bloodcrystals',
    628: 'Year of the Kobold Hordes',
    629: 'Year of the Empty Hearth',
    630: 'Year of the Winking Jester',
    631: 'Year of the Lone Lark',
    632: 'Year of the Burning Skies',
    633: 'Year of the Chasms',
    634: 'Year of the Darkspawn',
    635: "Year of the Soldier's Forfeit",
    636: 'Year of the Luminous Tabard',
    637: 'Year of the Silver Sun',
    638: 'Year of the Menial Phrases',
    639: "Year of Ire's Immolation",
    640: 'Year of the Fanged Beast',
    641: 'Year of the Necropolis',
    642: 'Year of the Sifting Sands',
    643: 'Year of the Nesting Harpy',
    644: 'Year of the Gleaming Gates',
    645: 'Year of the Costly Gift',
    646: 'Year of the Tormented Souls',
    647: 'Year of the Wayward Heart',
    648: 'Year of the Dancing Daggers',
    649: 'Year of the Bloody Crown',
    650: 'Year of the Falling Tower',
    651: 'Year of the Waning Sun',
    652: 'Year of the Viper',
    653: 'Year of the Killing Blow',
    654: 'Year of the Coveted Briars',
    655: 'Year of the Volanth',
    656: 'Year of Peaceful Seas',
    657: 'Year of the Nine Stars',
    658: 'Year of the Dangerous Game',
    659: 'Year of the Hunting Ghosts',
    660: 'Year of the Morning Horn',
    661: 'Year of the Bloody Tusk',
    662: "Year of the Peoples' Mourning",
    663: 'Year of the Baleful Song',
    664: 'Year of the Stern Judgement',
    665: 'Year of the Ashen Tears',
    666: 'Year of the Stern Judgement',
    667: 'Year of Austere Ceremonies',
    668: 'Year of the Telling Tome',
    669: 'Year of the Brutal Beast',
    670: 'Year of the Many Floods',
    671: 'Year of the Shrouded Slayer',
    672: 'Year of the Angry Caverns',
    673: 'Year of the Covenant',
    674: 'Year of the Nomad',
    675: 'Year of the Bloodfeud',
    676: 'Year of the Scarlet Sash',
    677: 'Year of the Resonant Silence',
    678: 'Year of the Scarlet Sash',
    679: 'Year of the Scarlet Sash',
    680: 'Year of the Long March',
    681: 'Year of the Zombie Lords',
    682: 'Year of the Howling',
    683: 'Year of the Tainted Troll',
    684: 'Year of the Sundered Crypt',
    685: 'Year of the Wraithwinds',
    686: 'Year of the Unshriven',
    687: 'Year of the Wandering Sylph',
    688: 'Year of the Zephyr',
    689: 'Year of the Eager Executioner',
    690: 'Year of the Clashing Blades',
    691: 'Year of the Stricken Sun',
    692: 'Year of the Crawling Crags',
    693: 'Year of the Enigmatic Smile',
    694: 'Year of the Ominous Oracle',
    695: 'Year of Fanciful Feasts',
    696: 'Year of the Great Escape',
    697: "Year of the Triton's Horn",
    698: 'Year of the Voracious Vole',
    699: 'Year of Rampaging Raaserpents',
    700: 'Year of the Slain Raven',
    701: 'Year of the White Jonquil',
    702: 'Year of the Clutching Death',
    703: 'Year of the Shambling Ice',
    704: 'Year of the Emerald Citadel',
    705: 'Year of Watchful Eyes',
    706: 'Year of the Realmsrage',
    707: 'Year of Portents Perilous',
    708: 'Year of Bound Evils',
    709: 'Year of the Earnest Oaths',
    710: 'Year of the Toppled Throne',
    711: 'Year of Despairing Elves',
    712: 'Year of the Lost Lance',
    713: 'Year of the Firedrake',
    714: 'Year of Doom',
    715: 'Year of the Hungry Jaws',
    716: 'Year of Reaching Regret',
    717: "Year of the Druid's Wrath",
    718: 'Year of the Painful Price',
    719: 'Year of the Lost Lord',
    720: 'Year of Dawn Rose',
    721: 'Year of the Hungry Pool',
    722: 'Year of the Last Hunt',
    723: 'Year of the Underdark Afire',
    724: 'Year of the Prisoner Unfettered',
    725: 'Year of the Shorn Beard',
    726: 'Year of the Dowager Lady',
    727: 'Year of the Purloined Throne',
    728: 'Year of the Sleeping Princess',
    729: 'Year of the Twisted Horn',
    730: 'Year of the Jovial Mage',
    731: 'Year of Visions',
    732: 'Year of the Proud Father',
    733: 'Year of the Sad Refrains',
    734: 'Year of the Splendid Stag',
    735: "Year of the Prophet's Child",
    736: 'Year of the Gleeful Noise',
    737: 'Year of the Winded Herald',
    738: 'Year of the Gliding Man',
    739: 'Year of the Staggered Minotaur',
    740: 'Year of the Splendid Stag',
    741: 'Year of the Shandon Eyes',
    742: 'Year of Comrades-at-Arms',
    743: 'Year of the Snowy Addax',
    744: 'Year of the Jeweled Aerie',
    745: 'Year of the Jeweled Aerie',
    746: 'Year of the Jeweled Aerie',
    747: 'Year of the Stagnant Water',
    748: 'Year of the Coin',
    749: 'Year of the Jeweled Aerie',
    750: 'Year of the Dying Dwarf',
    751: 'Year of Good Tidings',
    752: 'Year of High Treachery',
    753: 'Year of Strife',
    754: "Year of Mid-Summer's Dreams",
    755: 'Year of the Enigma',
    756: 'Year of the Leaning Post',
    757: 'Year of Lost Wayfarers',
    758: 'Year of the Scorched Sea',
    759: 'Year of the Missing Blade',
    760: 'Year of Drifting Stars',
    761: 'Year of Laughter',
    762: 'Year of the Snow Sword',
    763: 'Year of the Sharp Edge',
    764: 'Year of the Mistmaidens',
    765: 'Year of the Cowl',
    766: 'Year of Yearning',
    767: 'Year of the Beast',
    768: 'Year of the Prying Gods',
    769: 'Year of the Torm Cloak',
    770: 'Year of the Diamond Sword',
    771: 'Year of the Stalking Knight',
    772: 'Year of the Giggling Ogre',
    773: 'Year of the Aurumvorax',
    774: 'Year of the Scowling Duchess',
    775: 'Year of the Bloody Stone',
    776: 'Year of the Crystal Ball',
    777: 'Year of the Fortified Mind',
    778: 'Year of Awaiting Webs',
    779: 'Year of the Crying Sphinx',
    780: 'Year of the Broken Crossbow',
    781: 'Year of the Elven Fortress',
    782: 'Year of the Gentle Hand',
    783: 'Year of the Lizard King',
    784: 'Year of the Shattered Tome',
    785: 'Year of the Manticore Rampant',
    786: 'Year of the Moaning Gorge',
    787: 'Year of the Rotting Orchard',
    788: 'Year of the True Believer',
    789: 'Year of the Flourishing Forests',
    790: 'Year of Bend Sinister',
    791: "Year of the Sister's Battles",
    792: 'Year of the Crimson Thorn',
    793: 'Year of the Furious Horse',
    794: 'Year of the Grimacing Elf',
    795: 'Year of the Firehawk',
    796: 'Year of the Gray Mists',
    797: 'Year of the Hearthstone',
    798: 'Year of the Holy Aspergill',
    799: 'Year of the Laughing Gull',
    800: 'Year of the Black Fist',
    801: 'Year of the Star Rose',
    802: 'Year of the Patchworked Peace',
    803: 'Year of the Reaching Hand',
    804: 'Year of the Spreading Scourge',
    805: 'Year of the Unsung Bard',
    806: "Year of the Warrior's Rest",
    807: 'Year of the Bearded Maiden',
    808: 'Year of the Crescent Moon',
    809: 'Year of the Boastful Noble',
    810: 'Year of the Dark Mystery',
    811: 'Year of Many Tears',
    812: 'Year of the Gem Dragons',
    813: 'Year of Widows',
    814: "Year of the Harper's Apprentice",
    815: 'Year of the Heavy Heart',
    816: 'Year of the Laughing Swan',
    817: 'Year of the Deadly Torch',
    818: 'Year of Broken Locks',
    819: 'Year of the Mendacious Page',
    820: 'Year of the Roving Tyrant',
    821: 'Year of the Firewall',
    822: "Year of the Wizard's Chalice",
    823: 'Year of the Floating Petals',
    824: 'Year of the Copper Coil',
    825: 'Year of the Silver Flagon',
    826: 'Year of Wolfpacks',
    827: 'Year of the Sacrificed Fortune',
    828: 'Year of Alarmed Merchants',
    829: 'Year of the Thessalhydra',
    830: 'Year of the Ambitious Proposal',
    831: 'Year of the Deceptive Tongue',
    832: 'Year of the Slow Herald',
    833: 'Year of the Flying Serpent',
    834: 'Year of the Leaping Lion',
    835: 'Year of the Billowed Sail',
    836: 'Year of Twelve Bells',
    837: 'Year of the Darkened Sundial',
    838: 'Year of the Unfettered Genie',
    839: 'Year of Ten Atonements',
    840: 'Year of the Fighting Sage',
    841: 'Year of the Hunted Elk',
    842: 'Year of the Maverick',
    843: 'Year of Amber',
    844: 'Year of the Midnight Sun',
    845: 'Year of the Ruby Pendant',
    846: 'Year of the Steadfast Dwarf',
    847: 'Year of the Unmarked Path',
    848: 'Year of the Vigilant Familiar',
    849: 'Year of the Black Book',
    850: 'Year of the Empty Throne',
    851: 'Year of the Jasmal Blade',
    852: 'Year of the False Smile',
    853: 'Year of the Hungry Box',
    854: 'Year of the Indigo Inferno',
    855: 'Year of the Cornerstones',
    856: 'Year of Thorns',
    857: 'Year of Forgotten Fame',
    858: 'Year of the Saffron Orb',
    859: 'Year of the Sea Crossing',
    860: 'Year of the Tired Horsemen',
    861: 'Year of the Exploding Orl',
    862: 'Year of the Snow Rose',
    863: 'Year of the Wondrous Sea',
    864: 'Year of the Broken Branch',
    865: 'Year of Flamedance',
    866: 'Year of the Blessed Morning',
    867: 'Year of the Cryptic Recipe',
    868: 'Year of the Endless Scroll',
    869: 'Year of the Final Price',
    870: 'Year of the Hooded Tracker',
    871: 'Year of the Marching Golem',
    872: 'Year of the Moonbar Crest',
    873: 'Year of the Opening Flower',
    874: 'Year of the Roiling Cauldron',
    875: 'Year of the Stricken Star',
    876: 'Year of the Toothless Skulls',
    877: 'Year of the Scratching Claw',
    878: 'Year of the Two-edged Axe',
    879: "Year of the Winter's Warmth",
    880: 'Year of Unfettered Secrets',
    881: 'Year of the Brazen Vizier',
    882: 'Year of the Curse',
    883: "Year of the Giant's Oath",
    884: 'Year of the Singing Arrows',
    885: 'Year of the Thistle',
    886: 'Year of the Fell Firebrake',
    887: 'Year of Fell Pearls',
    888: 'Year of Twelve Teeth',
    889: 'Year of the Shining Shield',
    890: 'Year of the Burning Tree',
    891: 'Year of the Leaning Keep',
    892: 'Year of the Open Tome',
    893: 'Year of the Raised Sword',
    894: 'Year of Cold Flame',
    895: 'Year of the Spitting Cat',
    896: 'Year of the Empty Hand',
    897: 'Year of the Calling Shrike',
    898: 'Year of the Common Corpse',
    899: 'Year of the Tolling Bell',
    900: 'Year of the Thirsty Sword',
    901: 'Year of the August Armathor',
    902: "Year of the Queen's Tears",
    903: 'Year of the Trial',
    904: 'Year of the Rising Maeran',
    905: 'Year of the Rotting Word',
    906: 'Year of the Plough',
    907: 'Year of Waiting',
    908: 'Year of the Lone Tribe',
    909: 'Year of the Ogre',
    910: 'Year of Deathblows Denied',
    911: 'Year of Ruins Reborn',
    912: 'Year of the Sudden Journey',
    913: 'Year of the Watching Raven',
    914: 'Year of the Book',
    915: 'Year of the Bats',
    916: 'Year of the Sinhala',
    917: 'Year of the Winding Road',
    918: 'Year of the Palace',
    919: 'Year of the Chase',
    920: 'Year of Great Riches',
    921: 'Year of the Falling Maeran',
    922: 'Year of the Spouting Fish',
    923: 'Year of the Bloodied Soldier',
    924: 'Year of the Cracked Turtle',
    925: 'Year of the Enchanted Trail',
    926: 'Year of the Fearless Peasant',
    927: 'Year of the Red Rain',
    928: 'Year of the Hurled Axe',
    929: 'Year of Flashing Eyes',
    930: 'Year of the Liberty Crest',
    931: 'Year of the Penitent Rogue',
    932: 'Year of Fireslaughter',
    933: 'Year of the Five Jugs',
    934: 'Year of Fell Wizardry',
    935: 'Year of the Rearing Lion',
    936: 'Year of the Sky Riders',
    937: 'Year of the Turning Wheel',
    938: 'Year of the Unhanged Man',
    939: 'Year of the Vengeful Halfling',
    940: 'Year of the Cold Claws',
    941: 'Year of Sudden Sorrows',
    942: 'Year of the Circling Vulture',
    943: 'Year of the Flying Steed',
    944: 'Year of the Animated Armor',
    945: 'Year of the Foolish Bridegroom',
    946: 'Year of the Blazing Call',
    947: 'Year of the Advancing Wind',
    948: 'Year of the Clarion Trumpet',
    949: 'Year of the Forbidden Tome',
    950: 'Year of the Doomguard',
    951: 'Year of the Empty Hourglass',
    952: 'Year of the Rings Royal',
    953: 'Year of the Guiding Crow',
    954: 'Year of Perilous Halls',
    955: 'Year of the Telltale Candle',
    956: 'Year of the Crooked Finger',
    957: 'Year of the Entombed Poet',
    958: 'Year of the Far-flung Harp',
    959: 'Year of the Haunted Crew',
    960: 'Year of the Mageling',
    961: 'Year of the Pensive Gibberling',
    962: 'Year of the Shandon Veil',
    963: 'Year of the Thundering Horde',
    964: 'Year of the Pickled Privateer',
    965: 'Year of the Runelightning',
    966: 'Year of the Squire',
    967: 'Year of the Tearful Princess',
    968: 'Year of the Wandering Gnome',
    969: 'Year of the Bright Standard',
    970: "Year of the Child's Trinket",
    971: 'Year of the Children',
    972: 'Year of the Cairngorm Crown',
    973: 'Year of the Emptied Lair',
    974: 'Year of the Haunting Harpy',
    975: 'Year of the Bent Coin',
    976: 'Year of the Slaying Spells',
    977: 'Year of Swordforging',
    978: 'Year of the Hooded Rogue',
    979: 'Year of the Marching Forest',
    980: 'Year of the Orator',
    981: 'Year of the Rebel Uprising',
    982: 'Year of the Watching Helm',
    983: 'Year of the Submerged Country',
    984: 'Year of the Caravan',
    985: 'Year of Bright Nights',
    986: 'Year of the Dusken Ride',
    987: 'Year of the Flaming Dwarf',
    988: 'Year of the Meddling Avatar',
    989: 'Year of Dark Stalking',
    990: 'Year of the Muster',
    991: 'Year of Breaking Ice',
    992: 'Year of the Watching Helm',
    993: 'Year of the Slain Mountain',
    994: 'Year of the Weary Scribe',
    995: 'Year of the Charging Mare',
    996: 'Year of the Disfiguring Scar',
    997: 'Year of the Fearful Harper',
    998: 'Year of Much Iron',
    999: 'Year of the Gaping Sky',
    1000: 'Year of the Wailing Winds',
    1001: 'Year of the Awakening',
    1002: 'Year of the Heavenly Rock',
    1003: 'Year of the Labyrinth',
    1004: "Year of the Oracle's Carcass",
    1005: 'Year of the Pillaged Crypt',
    1006: 'Year of the Second Son',
    1007: 'Year of the Bold Barbarian',
    1008: 'Year of the Treacherous Path',
    1009: 'Year of the Broken Spear',
    1010: 'Year of Three Signs',
    1011: 'Year of the Defiant Mountain',
    1012: 'Year of the Flamboyant Coif',
    1013: 'Year of the Hunted Whale',
    1014: 'Year of the Grimacing Sage',
    1015: 'Year of the Maid Enraged',
    1016: 'Year of the Roaring Tempest',
    1017: 'Year of the Stone Rose',
    1018: 'Year of the Dracorage',
    1019: 'Year of the Sure Quarrel',
    1020: 'Year of the Smoldering Spells',
    1021: 'Year of the Howling Axe',
    1022: 'Year of the Wandering Wyvern',
    1023: "Year of the Pirate's Trove",
    1024: "Year of Lathander's Light",
    1025: 'Year of Screaming Princesses',
    1026: 'Year of Crimson Magics',
    1027: 'Year of the Tempest',
    1028: 'Year of the Wistful Nymph',
    1029: 'Year of the Bold Strides',
    1030: 'Year of Warlords',
    1031: 'Year of the Comforting Hand',
    1032: 'Year of the Nightmaidens',
    1033: 'Year of the Dreamforging',
    1034: "Year of Bane's Brood",
    1035: 'Year of Falling Stars',
    1036: 'Year of the Final Test',
    1037: 'Year of the Immortals',
    1038: 'Year of Spreading Spring',
    1039: 'Year of the Haunted Haven',
    1040: "Year of the Lion's Heart",
    1041: 'Year of the Mistmarch Soldier',
    1042: 'Year of the Reaching Beacon',
    1043: 'Year of the Dark Rider',
    1044: 'Year of the Singing Shards',
    1045: 'Year of the Singing Mushrooms',
    1046: 'Year of the Twilight Campaign',
    1047: 'Year of the Vitriolic Sage',
    1048: 'Year of the Chevalier',
    1049: "Year of Auril's Absence",
    1050: 'Year of the Keening Gale',
    1051: 'Year of the Dogged Search',
    1052: 'Year of the Frozen Kingdoms',
    1053: 'Year of Lashing and Torment',
    1054: 'Year of Tolling Terrors',
    1055: 'Year of the Grueling Story',
    1056: 'Year of the Laughing Dead',
    1057: 'Year of Azure Frost',
    1058: "Year of the Spider's Daughter",
    1059: 'Year of the Broken Pillar',
    1060: 'Year of Fantastic Spectacle',
    1061: 'Year of the Pious Dance',
    1062: 'Year of the Shattered Lance',
    1063: 'Year of the Deluded Tyrant',
    1064: 'Year of the Stranger',
    1065: 'Year of the Watching Wood',
    1066: "Year of the Lord's Dilemma",
    1067: 'Year of the Minotaur Paladin',
    1068: 'Year of the Seer Born',
    1069: "Year of the Thunder's Child",
    1070: 'Year of the Spawning',
    1071: "Year of Lion's Roars",
    1072: 'Year of the Wandering Elfmaid',
    1073: 'Year of the Bottomless Ocean',
    1074: 'Year of the Rose',
    1075: 'Year of the Bronze Banner',
    1076: 'Year of the Defiant Salute',
    1077: 'Year of the Friendly Jackal',
    1078: 'Year of the Hierodulic Wolverines',
    1079: 'Year of the Lazy Scribe',
    1080: 'Year of the Misguided Archer',
    1081: 'Year of the the Disastrous Bauble',
    1082: 'Year of the Prancing Korred',
    1083: 'Year of the Sighted Hind',
    1084: 'Year of the Tireless Lute',
    1085: 'Year of the Vacant Plain',
    1086: "Year of the Seer's Fires",
    1087: 'Year of Forgotten Anger',
    1088: 'Year of Shambles',
    1089: 'Year of Three Faces',
    1090: 'Year of Slaughter',
    1091: 'Year of Watery Graves',
    1092: 'Year of the Aimless Mystic',
    1093: 'Year of the Bursting Song',
    1094: 'Year of the Crested Thrush',
    1095: 'Year of the Dawndance',
    1096: 'Year of the Diverged Path',
    1097: 'Year of the Gleaming Crown',
    1098: 'Year of the Rose',
    1099: 'Year of the Restless',
    1100: 'Year of the Bloodrose',
    1101: 'Year of the Maelstrom',
    1102: 'Year of the Chaste Maiden',
    1103: 'Year of the Consuming Glory',
    1104: 'Year of the Dark Dawn',
    1105: 'Year of the Guardian',
    1106: 'Year of the Solemn Halfling',
    1107: 'Year of the Skulk',
    1108: 'Year of the Open Chest',
    1109: "Year of the Lover's Eyes",
    1110: 'Year of the Bloody Fields',
    1111: 'Year of the Old Giant',
    1112: 'Year of the Perilous Storm',
    1113: 'Year of the Outcast Prophet',
    1114: 'Year of the Last Enclave',
    1115: 'Year of the Haunted Herald',
    1116: 'Year of the Empty Scabbard',
    1117: 'Year of the Twelverule',
    1118: 'Year of the False Bargain',
    1119: 'Year of the Sharn Suitors',
    1120: 'Year of the Perplexing Sphinx',
    1121: 'Year of the Shameful Plea',
    1122: 'Year of the Rose Pearls',
    1123: 'Year of the Shattered Chains',
    1124: 'Year of the Shared Sorrows',
    1125: 'Year of the Lupine Torque',
    1126: 'Year of Azure Blood',
    1127: 'Year of the Luminar Procession',
    1128: 'Year of the Peryton',
    1129: 'Year of the Gilded Cormorant',
    1130: 'Year of the Howling Moon',
    1131: 'Year of the Seven Kings Horde',
    1132: 'Year of the Talking Spiders',
    1133: 'Year of the Persuasive Voice',
    1134: 'Year of the Sylvan Wards',
    1135: 'Year of the Petulant Dragon',
    1136: 'Year of the Shadowkin Return',
    1137: 'Year of the Falling Menhirs',
    1138: 'Year of the Sharpened Teeth',
    1139: 'Year of Shining Waves',
    1140: 'Year of the Knight',
    1141: 'Year of Eyes',
    1142: "Year of the Sword's Oath",
    1143: 'Year of the Talisman',
    1144: "Year of the Giant's Maul",
    1145: 'Year of the Smiling Flame',
    1146: 'Year of the Tardy Guests',
    1147: 'Year of the Glad Tidings',
    1148: 'Year of the Angry Sea',
    1149: 'Year of the Persuasive Trees',
    1150: 'Year of the Scourge',
    1151: 'Year of the Molten Man',
    1152: 'Year of the Portentous Waters',
    1153: 'Year of the Remembering Stones',
    1154: 'Year of the Sun Underground',
    1155: "Year of the Tyrant's Lament",
    1156: 'Year of the Winged Gift',
    1157: 'Year of the Wizened Mage',
    1158: 'Year of the Blood Tusk Charge',
    1159: 'Year of the Cloven Stones',
    1160: 'Year of the Swimming Lass',
    1161: 'Year of the Quiet Earth',
    1162: 'Year of the Prancing Centaur',
    1163: 'Year of the Shrouded Sky',
    1164: 'Year of the Long Shadows',
    1165: 'Year of the Obsidian Heart',
    1166: 'Year of the Countless Scribes',
    1167: 'Year of the Parchment Heretical',
    1168: 'Year of the Leering Orc',
    1169: 'Year of the Earth Shaking',
    1170: 'Year of the Moonlight Tapestry',
    1171: 'Year of the Dark Mask',
    1172: 'Year of the Hoary Host',
    1173: 'Year of the Fledglings',
    1174: 'Year of the Agate Hammer',
    1175: 'Year of the Storm Skeleton',
    1176: 'Year of Prowling Naga',
    1177: 'Year of the Majesty',
    1178: 'Year of the Secret Rider',
    1179: 'Year of the Stalking Satyr',
    1180: 'Year of Sinking Sails',
    1181: 'Year of the Shieldtree',
    1182: 'Year of the Tomb',
    1183: 'Year of the Grisly Ghost',
    1184: 'Year of the Howling Hourglass',
    1185: 'Year of the Immoral Imp',
    1186: 'Year of the Mesmer Pool',
    1187: 'Year of the Arcane Guise',
    1188: 'Year of the Soft Fogs',
    1189: 'Year of the Lynx',
    1190: 'Year of the Poisoned Quill',
    1191: 'Year of the Bone Helm',
    1192: 'Year of the Guide',
    1193: 'Year of the Peltast',
    1194: 'Year of the Bloody Wave',
    1195: 'Year of the Midday Mists',
    1196: 'Year of the Shrike',
    1197: 'Year of the Sundered Shields',
    1198: 'Year of the Lean Purse',
    1199: 'Year of the Baldric',
    1200: 'Year of the Buckler',
    1201: 'Year of Embers',
    1202: 'Year of the Dragon Altar',
    1203: 'Year of the Gold Sash',
    1204: 'Year of Private Tears',
    1205: 'Year of Seven Trinkets',
    1206: 'Year of the Sarune',
    1207: 'Year of the Bloated Baron',
    1208: 'Year of the Gamine',
    1209: 'Year of the Blazing Banners',
    1210: 'Year of the Armarel',
    1211: 'Year of the Crimson Crag',
    1212: "Year of Ocean's Wrath",
    1213: "Year of the Night's Peace",
    1214: 'Year of the Waking Wrath',
    1215: 'Year of Starlight',
    1216: 'Year of the Green Wings',
    1217: 'Year of the Falling Moon',
    1218: 'Year of the Swimming Cats',
    1219: 'Year of Prideful Tales',
    1220: 'Year of the Toppled Tree',
    1221: 'Year of the Frozen Flower',
    1222: 'Year of the Horn',
    1223: 'Year of the Trembling Tree',
    1224: 'Year of the Swollen Stars',
    1225: 'Year of the Winged Worm',
    1226: 'Year of the Black Buck',
    1227: 'Year of the Wall',
    1228: 'Year of the Tattered Banners',
    1229: 'Year of the Carrion Crow',
    1230: 'Year of the Long Watch',
    1231: 'Year of the Bright Star',
    1232: 'Year of the Weeping Wives',
    1233: 'Year of the Many Monsters',
    1234: 'Year of the Full Flagon',
    1235: 'Year of the Black Horde',
    1236: 'Year of the Struck Gong',
    1237: 'Year of the Grotto',
    1238: 'Year of the Lone Candle',
    1239: 'Year of the Bloodied Sword',
    1240: 'Year of the Bright Sun',
    1241: 'Year of the Lost Lady',
    1242: 'Year of the Yellow Rose',
    1243: 'Year of the Blue Dragon',
    1244: 'Year of the Defiant Keep',
    1245: 'Year of Pain',
    1246: 'Year of Burning Steel',
    1247: 'Year of the Purple Basilisk',
    1248: 'Year of the Cockatrice',
    1249: 'Year of the Bold Knight',
    1250: 'Year of the Riven Skull',
    1251: 'Year of the Wandering Winds',
    1252: 'Year of the Empty Goblet',
    1254: 'Year of the Silent Steel',
    1255: 'Year of the Raging Flame',
    1256: 'Year of the Dusty Throne',
    1257: 'Year of the Killing Wave',
    1258: 'Year of the Wilted Flowers',
    1259: 'Year of the Vigilant Fist',
    1260: 'Year of the Broken Blade',
    1261: 'Year of Bright Dreams',
    1262: 'Year of the Black Wind',
    1263: 'Year of the Tressym',
    1264: 'Year of the Shattered Altar',
    1265: 'Year of Flowers',
    1266: 'Year of the Leaping Frog',
    1267: 'Year of the Groaning Hart',
    1268: 'Year of the Daystars',
    1269: 'Year of the Moat',
    1270: 'Year of the Tooth',
    1271: 'Year of the Shattered Well',
    1272: 'Year of the Shrieker',
    1273: 'Year of the Wagon',
    1274: 'Year of the Purple Toad',
    1275: 'Year of the Blade',
    1276: 'Year of the Crumbling Keep',
    1277: 'Year of the Beholder',
    1278: 'Year of Many Bones',
    1279: 'Year of the Snarling Dragon',
    1280: 'Year of the Manticore',
    1281: 'Year of the Cold Soul',
    1282: 'Year of Many Mists',
    1283: 'Year of the Crawling Clouds',
    1284: 'Year of the Dying Stars',
    1285: 'Year of the Blacksnake',
    1286: 'Year of the Rock',
    1287: 'Year of the Smoky Moon',
    1288: 'Year of the Roaring Horn',
    1289: 'Year of the Sighing Serpent',
    1290: 'Year of the Whelm',
    1291: 'Year of the Deep Moon',
    1292: 'Year of the Wandering Waves',
    1293: 'Year of the Talking Skull',
    1294: 'Year of the Deep Moon',
    1295: 'Year of the Ormserpent',
    1296: 'Year of the Black Hound',
    1297: 'Year of the Singing Skull',
    1298: 'Year of the Pointed Bone',
    1299: 'Year of the Claw',
    1300: 'Year of the Starfall',
    1301: 'Year of the Trumpet',
    1302: 'Year of Broken Helm',
    1303: 'Year of the Evening Sun',
    1304: 'Year of the Stag',
    1305: 'Year of the Creeping Fang',
    1306: 'Year of Thunder',
    1307: 'Year of the Mace',
    1308: 'Year of the Catacombs',
    1309: 'Year of the Sunset Winds',
    1310: 'Year of Storms',
    1311: 'Year of the Fist',
    1312: 'Year of the Griffon',
    1313: 'Year of the Shattered Oak',
    1314: 'Year of the Shadowtop',
    1315: 'Year of Spilled Blood',
    1316: 'Year of the Gulagoar',
    1317: 'Year of the Wandering Wyrm',
    1318: 'Year of the Tired Treant',
    1319: 'Year of the Fallen Throne',
    1320: 'Year of the Watching Cold',
    1321: 'Year of Chains',
    1322: 'Year of Lurking Death',
    1323: 'Year of Dreamwebs',
    1324: 'Year of the Grimoire',
    1325: 'Year of the Great Harvests',
    1326: 'Year of the Striking Hawk',
    1327: 'Year of the Blue Flame',
    1328: 'Year of the Adder',
    1329: 'Year of the Lost Helm',
    1330: 'Year of the Marching Moon',
    1331: 'Year of the Leaping Dolphin',
    1332: 'Year of the Sword and Stars',
    1333: 'Year of the Striking Falcon',
    1334: 'Year of the Blazing Brand',
    1335: 'Year of the Snow Winds',
    1336: 'Year of the Highmantle',
    1337: 'Year of Wandering Maiden',
    1338: 'Year of the Wanderer',
    1339: 'Year of the Weeping Moon',
    1340: 'Year of the Lion',
    1341: 'Year of the Gate',
    1342: 'Year of the Behir',
    1343: 'Year of the Boot',
    1344: 'Year of Moonfall',
    1345: 'Year of the Saddle',
    1346: 'Year of the Bloodbird',
    1347: 'Year of the Bright Blade',
    1348: 'Year of the Spur',
    1349: 'Year of the Bridle',
    1350: 'Year of the Morningstar',
    1351: 'Year of the Crown',
    1352: 'Year of the Dragon',
    1353: 'Year of the Arch',
    1354: 'Year of the Bow',
    1355: 'Year of the Harp',
    1356: 'Year of the Worm',
    1357: 'Year of the Prince',
    1358: 'Year of Shadows',
    1359: 'Year of the Serpent',
    1360: 'Year of the Turret',
    1361: 'Year of Maidens',
    1362: 'Year of the Helm',
    1363: 'Year of the Wyvern',
    1364: 'Year of the Wave',
    1365: 'Year of the Sword',
    1366: 'Year of the Staff',
    1367: 'Year of the Shield',
    1368: 'Year of the Banner',
    1369: 'Year of the Gauntlet',
    1370: 'Year of the Tankard',
    1371: 'Year of the Unstrung Harp',
    1372: 'Year of Wild Magic',
    1373: 'Year of Rogue Dragons',
    1374: 'Year of Lightning Storms',
    1375: 'Year of Risen Elfkin',
    1376: 'Year of the Bent Blade',
    1377: 'Year of the Haunting',
    1378: 'Year of the Cauldron',
    1379: 'Year of the Lost Keep',
    1380: 'Year of the Blazing Hand',
    1381: 'Year of the Starving',
    1382: 'Year of the Black Blazon',
    1383: 'Year of the Vindicated Warrior',
    1384: 'Year of Three Streams Blooded',
    1385: 'Year of Blue Fire',
    1386: "Year of the Halfling's Lament",
    1387: 'Year of the Emerald Ermine',
    1388: 'Year of the Tanarukka',
    1389: 'Year of the Forgiven Foes',
    1390: 'Year of the Walking Man',
    1391: 'Year of the Wrathful Eye',
    1392: 'Year of the Scroll',
    1393: 'Year of the Ring',
    1394: 'Year of Deaths Unmourned',
    1395: 'Year of Silent Death',
    1396: 'Year of the Secret',
    1397: 'Year of the Quill',
    1398: 'Year of the Voyage',
    1399: 'Year of the Fallen Friends',
    1400: 'Year of Lost Ships',
    1401: 'Year of the Sheltered Viper',
    1402: 'Year of the Exorcised Helm',
    1403: 'Year of the Hidden Harp',
    1404: 'Year of the Sceptered One',
    1405: 'Year of the Golden Mask',
    1406: 'Year of the Blackened Moon',
    1407: 'Year of the Halls Unhaunted',
    1408: 'Year of the Solitary Cloister',
    1409: 'Year of True Omens',
    1410: 'Year of the Eight-legged Mount',
    1411: 'Year of the Wrathful Vizier',
    1412: 'Year of the Dauntless Dwarves',
    1413: 'Year of Sunken Vessels',
    1414: 'Year of Sea Lions Roaring',
    1415: 'Year of the Staves Arcane',
    1416: 'Year of the Enthroned Puppet',
    1417: "Year of the Phaerimm's Vengeance",
    1418: "Year of the Lords' Coronation",
    1419: 'Year of the Empty Necropolis',
    1420: 'Year of the Dark Goddess',
    1421: 'Year of the Walking Trees',
    1422: 'Year of the Advancing Shadows',
    1423: 'Year of Thundering Hosts',
    1424: 'Year of the Dog-Eared Journal',
    1425: 'Year of Seven Sisters',
    1426: 'Year of the Dozen Dwarves',
    1427: 'Year of the Shalarins Surfacing',
    1428: "Year of the Elfqueen's Joy",
    1429: 'Year of the Ten Terrors',
    1430: 'Year of Stalking Horrors',
    1431: 'Year of the Lashing Tail',
    1432: 'Year of Silent Thunder',
    1433: 'Year of the Silent Departure',
    1434: 'Year of the Silent Crickets',
    1435: 'Year of the Silent Bell',
    1436: 'Year of Silent Shadows',
    1437: 'Year of the Silent Flute',
    1438: 'Year of Silent Waterfalls',
    1439: 'Year of the Silent Tear',
    1440: "Year of Azuth's Woe",
    1441: 'Year of Resurrections Rampant',
    1442: 'Year of Darkenbeasts Risen',
    1443: 'Year of Silver Bell Tolling',
    1444: 'Year of the Seductive Cambion',
    1445: 'Year of the Malachite Throne',
    1446: "Year of the Queen's Honor",
    1447: 'Year of the Fallen Tower',
    1448: 'Year of Neomen Swords',
    1449: 'Year of the Godly Invitation',
    1450: 'Year of Holy Thunder',
    1451: 'Year of Knowledge Unearthed',
    1452: 'Year of the Impatient Son',
    1453: 'Year of the Strangled Jester',
    1454: 'Year of the Emerald Sun',
    1455: "Year of the King's Repentance",
    1456: 'Year of the Mithral Hammer',
    1457: 'Year of the Lightning Strikes',
    1458: 'Year of the Plotting Priests',
    1459: 'Year of the Forged Sigil',
    1460: 'Year of the Malachite Shadows',
    1461: 'Year of Three Goddesses Blessing',
    1462: "Year of the Elves' Weeping",
    1463: 'Year of the Reborn Hero',
    1464: 'Year of the Six-Armed Elf',
    1465: 'Year of the Elven Swords Returned',
    1466: 'Year of the Mages in Amber',
    1467: 'Year of the Three Heroes United',
    1468: 'Year of the First Circle',
    1469: 'Year of Splendors Burning',
    1470: 'Year of the Second Circle',
    1471: 'Year of the Plagued Lords',
    1472: 'Year of the Third Circle',
    1473: "Year of the Heretic's Rampage",
    1474: 'Year of the Fourth Circle',
    1475: 'Year of the Final Stand',
    1476: 'Year of the Fifth Circle',
    1477: 'Year of the Purloined Statue',
    1478: 'Year of the Dark Circle',
    1479: 'Year of the Ageless One',
    1480: 'Year of Deep Water Drifting',
    1481: 'Year of the Grinning Halfling',
    1482: 'Year of the Narthex Murders',
    1483: 'Year of the Tasked Weasel',
    1484: 'Year of the Awakened Sleepers',
    1485: "Year of the Iron Dwarf's Vengeance",
    1486: 'Year of the Nether Mountain Scrolls',
    1487: 'Year of the Rune Lords Triumphant',
    1488: 'Year of Dwarvenkind Reborn',
    1489: 'Year of the Warrior Princess',
    1490: "Year of the Star Walker's Return",
    1491: 'Year of the Scarlet Witch',
    1492: 'Year of Three Ships Sailing',
    1493: 'Year of the Purple Dragons',
    1494: 'Year of Twelve Warnings',
    1495: "Year of the Tyrant's Pawn",
    1496: 'Year of the Duplicitous Courtier',
    1497: 'Year of the Palls Purple',
    1498: 'Year of the Black Regalia',
    1499: 'Year of the Desperate Gambit',
    1500: "Year of the Sea's Secrets Revealed",
    1501: 'Year of the Shining Mythal',
    1502: 'Year of the Pox Plague',
    1503: 'Year of the Haunted Inn',
    1504: 'Year of the Conquering Queen',
    1505: 'Year of Ogres Marching',
    1506: 'Year of the Discarded Shields',
    1507: 'Year of the Glowing Onyx',
    1508: 'Year of the Legend Reborn',
    1509: 'Year of the Sea Lion',
    1510: 'Year of the Treasure Abandoned',
    1511: 'Year of the Lion Rampant',
    1512: 'Year of the Shattered Mirror',
    1513: 'Year of the Tawny Feline',
    1514: 'Year of the Lost Wagers',
    1515: 'Year of the Howling Ghouls',
    1516: "Year of the Hangman's Joke",
    1517: 'Year of the Coward Rewarded',
    1518: 'Year of the Adomal Tapestry',
    1519: 'Year of the Deceitful Brother',
    1520: 'Year of the Arcane',
    1521: 'Year of the Moon Harp Restored',
    1522: 'Year of the Bored Phylls',
    1523: "Year of the Brownie's Delight",
    1524: 'Year of the Captive Harper',
    1525: 'Year of the Drawn Line',
    1526: 'Year of the Hazy Coast',
    1527: 'Year of the Hoard Retaken',
    1528: 'Year of the Insufferable Mystic',
    1529: "Year of the Horseman's Triumph",
    1530: 'Year of the Long-toothed Tiger',
    1531: 'Year of the Oozing Bog',
    1532: 'Year of the Locked Crypt',
    1533: 'Year of the Misshapen Mage',
    1534: 'Year of the Pale Lords',
    1535: 'Year of the Laurel Wreath',
    1536: 'Year of the Mirrored Face',
    1537: "Year of the Jungle's Vengeance",
    1538: 'Year of the Stalking Tiger',
    1539: 'Year of the Thoughtless Suitor',
    1540: 'Year of the Lifeless Archdruid',
    1541: 'Year of the Mirthful House',
    1542: 'Year of the Painted Grin',
    1543: 'Year of the Sacred Sceptre',
    1544: 'Year of Shadow Fiends',
    1545: 'Year of the Undying March',
    1546: 'Year of the Winter Rose',
    1547: 'Year of Dungeons Reclaimed',
    1548: 'Year of the Handsome Deal',
    1549: 'Year of the Meandering Archipelago',
    1550: 'Year of the Scarlet Tabard',
    1551: 'Year of the Misty Grave',
    1552: 'Year of the Overflowing Cup',
    1585: 'Year of the Bloodied Manacles',
    1587: 'Year of the Long Silence',
    1588: 'Year of the Swarming Ravens',
    1600: 'Year of Unseen Enemies',
}
